language: go

env:
  - COVERALLS_TOKEN=sW1SPRRXgQPGUiUmt43mTkMUzrsyqIBY7
  - GO111MODULE=on
before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  - go get github.com/Masterminds/glide
install:
  - go get
script:
    - go test -race -v ./...
    - chmod +x coveralls.bash
    - ./coveralls.bash
go:
  - 1.12.1